-- Seed community resources database
insert into public.community_resources (name, type, description, eligibility, application_link, contact_details, address, city, state, postal_code, latitude, longitude, verified, tags)
values
  (
    'National Overseas Scholarship',
    'scheme',
    'Indian Government scheme offering financial assistance to low-income students from marginalized communities to pursue Masters and Ph.D. degrees abroad.',
    '{"min_academic_score": "60%", "max_annual_family_income_inr": 800000, "max_age": 35}'::jsonb,
    'https://nosmsje.gov.in/',
    'nosmsje-support@gov.in',
    'Shastri Bhawan, Dr. Rajendra Prasad Road',
    'New Delhi',
    'Delhi',
    '110001',
    28.6139,
    77.2090,
    true,
    '["Government", "Scholarship", "Study Abroad"]'::jsonb
  ),
  (
    'PM YUVA Yojana (Pradhan Mantri Yuva Udyamita Vikas Abhiyan)',
    'scheme',
    'Ministry of Skill Development & Entrepreneurship scheme providing entrepreneurship training, mentorship support, and incubator access to student builders.',
    '{"target_audience": "Students, trainees, and young citizens interested in launching a startup"}'::jsonb,
    'https://www.msde.gov.in/',
    'pm.yuva@gov.in',
    'MSDE, Shram Shakti Bhawan, Rafi Marg',
    'New Delhi',
    'Delhi',
    '110001',
    28.6139,
    77.2090,
    true,
    '["Startup", "Mentorship", "Government"]'::jsonb
  ),
  (
    'Tata Scholarship at Cornell University',
    'scholarship',
    'Fully funded scholarship fund established by the Tata Education and Development Trust for Indian students accepted into undergraduate programs at Cornell University.',
    '{"admission_required": "Cornell University Undergraduate Program", "nationality": "Indian citizen", "need_based": true}'::jsonb,
    'https://admissions.cornell.edu/apply/international-applicants/tata-scholarship',
    'tata-trust-scholarships@cornell.edu',
    'Cornell University admissions office, Day Hall',
    'Ithaca',
    'New York',
    '14853',
    42.4534,
    -76.4735,
    true,
    '["Ivy League", "Undergraduate", "Need-Based"]'::jsonb
  ),
  (
    'Google Career Certificates (Coursera)',
    'certification',
    'Free scholarship voucher pathways to complete Google certified courses in IT Support, UX Design, Data Analytics, Project Management, and Cybersecurity.',
    '{"no_degree_required": true, "focus_areas": ["IT", "Analytics", "Project Management", "UX", "Security"]}'::jsonb,
    'https://grow.google/intl/en_in/certificates/',
    'support@coursera.org',
    'Online / Global',
    'Online',
    'Global',
    '000000',
    0.0,
    0.0,
    true,
    '["Self-Paced", "Technical", "Industry Certification"]'::jsonb
  ),
  (
    'NIMHANS Tele-MANAS Wellness Support',
    'wellness',
    'National mental health helpline and clinical guidance center offering 24/7 free counseling, psychological support, and stress management for students.',
    '{"free_services": true, "confidential": true}'::jsonb,
    'https://nimhans.ac.in/',
    'Toll Free: 14416',
    'NIMHANS campus, Hosur Road',
    'Bangalore',
    'Karnataka',
    '560029',
    12.9362,
    77.5975,
    true,
    '["Mental Wellness", "Counseling", "24/7 Helpline"]'::jsonb
  ),
  (
    'AICTE Pragati Scholarship for Girls',
    'scholarship',
    'Government scholarship scheme implemented by AICTE promoting technical education (Degree or Diploma) among female students.',
    '{"max_annual_family_income_inr": 800000, "gender": "Female", "course_type": "Technical Degree/Diploma"}'::jsonb,
    'https://www.aicte-india.org/schemes/students-development-schemes',
    'pragati@aicte-india.org',
    'AICTE HQ, Nelson Mandela Marg, Vasant Kunj',
    'New Delhi',
    'Delhi',
    '110070',
    28.5446,
    77.1554,
    true,
    '["Girls Education", "Technical Degree", "Government"]'::jsonb
  ),
  (
    'NASSCOM Career Fair & Tech Internship Event',
    'job_fair',
    'National job fair and networking summit connecting tech graduates, coders, and developers directly with MNCs, startups, and internship roles.',
    '{"qualification": "B.E/B.Tech/MCA/BSc/BCA", "experience": "0-2 years"}'::jsonb,
    'https://nasscom.in/events',
    'events@nasscom.in',
    'Sector 126',
    'Noida',
    'Uttar Pradesh',
    '201303',
    28.5355,
    77.3910,
    true,
    '["Tech Jobs", "Recruitment", "Internship Opportunities"]'::jsonb
  ),
  (
    'SEWA Community Digital Literacy Center',
    'center',
    'Self-Employed Womens Association center providing digital literacy libraries, computer labs, and office tools training programs.',
    '{"free_training": true, "target": "Women & Marginalized youths"}'::jsonb,
    'https://www.sewa.org/',
    'sewa- Ahmedabad@sewa.org',
    'SEWA Reception Center, Opp. Victoria Garden, Bhadra',
    'Ahmedabad',
    'Gujarat',
    '380001',
    23.0225,
    72.5714,
    true,
    '["Digital Literacy", "Women Empowerment", "Skills Training"]'::jsonb
  ),
  (
    'CRY (Child Rights and You) Youth Fellowships',
    'ngo',
    'NGO fellowship for students advocating children rights, developing social impact projects, and volunteering in community learning initiatives.',
    '{"min_age": 18, "weekly_commitment_hours": 6}'::jsonb,
    'https://www.cry.org/volunteer-with-cry/',
    'cryinfo.del@crymail.org',
    'Madhusudan Mukerjee Road, Khardah',
    'Kolkata',
    'West Bengal',
    '700116',
    22.7230,
    88.3780,
    true,
    '["Social Impact", "Fellowship", "NGO"]'::jsonb
  ),
  (
    'Asha for Education Teaching Fellowships',
    'ngo',
    'Teaching internship and volunteering program in regional educational centers. Participants gain classroom experience and receive certificates.',
    '{"academic_background": "Any stream", "commitment_months": 3}'::jsonb,
    'https://ashanet.org/',
    'fellowships@ashanet.org',
    'IIT Madras Campus, Adyar',
    'Chennai',
    'Tamil Nadu',
    '600036',
    13.0067,
    80.2400,
    true,
    '["Teaching", "Rural Education", "Volunteering"]'::jsonb
  ),
  (
    'Sama Mental Health & Student Support Hub',
    'wellness',
    'A regional wellness organization offering free student counseling, peer support programs, and mental health workshops.',
    '{"free_sessions": true, "peer_support": true}'::jsonb,
    'https://www.samamind.org/',
    'contact@samamind.org',
    'Deccan Gymkhana',
    'Pune',
    'Maharashtra',
    '411004',
    18.5204,
    73.8567,
    true,
    '["Mental Wellness", "Student Counsel", "Workshops"]'::jsonb
  ),
  (
    'IBM SkillsBuild Portal',
    'certification',
    'Global online program offering free badges and certificates in Emerging Technologies like Cloud, AI, Cyber Security, Agile, and Career Skills.',
    '{"no_prior_tech_knowledge_required": true}'::jsonb,
    'https://skillsbuild.org/',
    'skillsbuild-support@ibm.com',
    'Online / Global',
    'Online',
    'Global',
    '000000',
    0.0,
    0.0,
    true,
    '["IBM Badge", "Cloud Computing", "AI Fundamentals"]'::jsonb
  ),
  (
    'Microsoft YouthSpark Internships',
    'internship',
    'Internship pathways and skill-building programs targeted at students from underrepresented communities.',
    '{"enrolled_in_college": true, "stem_preference": true}'::jsonb,
    'https://careers.microsoft.com/',
    'youthspark-hyd@microsoft.com',
    'Microsoft Campus, Gachibowli',
    'Hyderabad',
    'Telangana',
    '500032',
    17.4483,
    78.3741,
    true,
    '["Tech Intern", "Microsoft", "STEM Support"]'::jsonb
  ),
  (
    'Pradhan Mantri Kaushal Vikas Yojana (PMKVY) Center',
    'center',
    'Skill training center offering vocational certifications in coding, software testing, hardware maintenance, and data management.',
    '{"min_qualification": "Class 10/12 pass", "free_training": true}'::jsonb,
    'https://www.pmkvyofficial.org/',
    'pmkvy-helpdesk@nsdcindia.org',
    'Malviya Nagar Industrial Area',
    'Jaipur',
    'Rajasthan',
    '302017',
    26.8524,
    75.8073,
    true,
    '["Vocational Training", "Government Scheme", "Coding Basics"]'::jsonb
  ),
  (
    'Samaritans Mumbai Suicide Prevention Helpline',
    'wellness',
    'Helpline and walk-in center offering confidential, anonymous emotional support for students facing severe exam stress, depression, or anxiety.',
    '{"free_services": true, "helpline_number": "+91 84229 84528"}'::jsonb,
    'http://www.samaritansmumbai.org/',
    'samaritans.helpline@gmail.com',
    'Mahim West',
    'Mumbai',
    'Maharashtra',
    '400016',
    19.0345,
    72.8402,
    true,
    '["Suicide Helpline", "Crisis Intervention", "Emotional Support"]'::jsonb
  ),
  (
    'Vidyasaarathi Scholarship Portal',
    'scholarship',
    'Portal matching students with various corporate CSR scholarships based on income limits and merit parameters.',
    '{"max_annual_family_income_inr": 600000, "course_type": "Degree/Diploma"}'::jsonb,
    'https://www.vidyasaarathi.co.in/',
    'vidyasaarathi@nsdl.co.in',
    'NSDL, Lower Parel',
    'Mumbai',
    'Maharashtra',
    '400013',
    19.0020,
    72.8280,
    true,
    '["CSR Funding", "Merit Scholarship", "Education Grants"]'::jsonb
  ),
  (
    'Swayam NPTEL Online Courses',
    'certification',
    'Ministry of Education initiative offering free high-quality courses designed by IIT faculty with an option to pay a nominal fee for physical exams & certificates.',
    '{"open_for_all": true, "exam_credit_transfer_allowed": true}'::jsonb,
    'https://swayam.gov.in/',
    'support@swayam.gov.in',
    'IIT Madras NPTEL office',
    'Chennai',
    'Tamil Nadu',
    '600036',
    13.0067,
    80.2400,
    true,
    '["IIT Certified", "Free Learning", "Credit Transfer"]'::jsonb
  ),
  (
    'Goonj School to School Fellowship',
    'ngo',
    'A youth internship program with Goonj focusing on operational planning, rural community resource mapping, and supply chain management.',
    '{"min_age": 21, "fellowship_duration_months": 12}'::jsonb,
    'https://goonj.org/goonj-fellowship/',
    'mail@goonj.org',
    'Sarita Vihar',
    'New Delhi',
    'Delhi',
    '110076',
    28.5298,
    77.2912,
    true,
    '["Social Development", "Goonj Fellowship", "NGO Intern"]'::jsonb
  ),
  (
    'Delhi State Merit-cum-Means Scholarships',
    'student_service',
    'Delhi Government support services providing financial assistance to college students of state universities.',
    '{"residency": "Delhi resident", "max_annual_family_income_inr": 600000}'::jsonb,
    'https://edistrict.delhigovt.nic.in/',
    'edistrict-support@delhi.gov.in',
    'IP Estate, ITO',
    'New Delhi',
    'Delhi',
    '110002',
    28.6272,
    77.2472,
    true,
    '["State Government", "Need-Based", "Colleges"]'::jsonb
  ),
  (
    'Youth Ki Awaaz Writers Mentorship',
    'mentorship',
    'A competitive digital mentorship program for student writers and change-makers focusing on editing, storytelling, and digital advocacy.',
    '{"age_limit": "18-25", "passion_for_writing": true}'::jsonb,
    'https://www.youthkiawaaz.com/join-yka-mentorship/',
    'careers@youthkiawaaz.com',
    'Online / Global',
    'Online',
    'Global',
    '000000',
    0.0,
    0.0,
    true,
    '["Mentorship", "Journalism", "Advocacy"]'::jsonb
  ),
  (
    'Kishore Vaigyanik Protsahan Yojana (KVPY)',
    'scholarship',
    'National science fellowship program funded by DST to identify and encourage talented students to take up research careers.',
    '{"academic_level": "Class 11/12/Undergrad", "stream": "Basic Sciences"}'::jsonb,
    'http://kvpy.iisc.ernet.in/',
    'kvpy.office@iisc.ac.in',
    'IISc campus',
    'Bangalore',
    'Karnataka',
    '560012',
    13.0219,
    77.5671,
    true,
    '["Fellowship", "IISc", "Research Career"]'::jsonb
  ),
  (
    'Teach For India Fellowship',
    'ngo',
    'A full-time, two-year paid leadership program where students teach in under-resourced schools, receiving extensive leadership training and corporate mentorship.',
    '{"graduation_status": "Graduate by June 2026", "nationality": "Indian citizen/OCI"}'::jsonb,
    'https://www.teachforindia.org/fellowship',
    'apply@teachforindia.org',
    'Yerawada',
    'Pune',
    'Maharashtra',
    '411006',
    18.5534,
    73.8867,
    true,
    '["Paid Fellowship", "Education Equity", "NGO leadership"]'::jsonb
  ),
  (
    'AWS Educate Free Cloud Pathways',
    'certification',
    'Amazon initiative providing students with free cloud compute credits, self-paced learning pathways, and access to the AWS Educate Job Board.',
    '{"student_status": "Enrolled student", "min_age": 13}'::jsonb,
    'https://aws.amazon.com/education/awseducate/',
    'aws-educate@amazon.com',
    'Online / Global',
    'Online',
    'Global',
    '000000',
    0.0,
    0.0,
    true,
    '["AWS cloud", "Badges", "AWS Credits"]'::jsonb
  ),
  (
    'Bangalore Tech Job Fair 2026',
    'job_fair',
    'Multi-sector hiring fair organized by state labor department focusing on engineering, vocational graduates, and administrative roles.',
    '{"open_for_all": true, "entry_fee": "Free"}'::jsonb,
    'https://www.karnataka.gov.in/',
    'jobfair-support.kar@nic.in',
    'Kanteerava Indoor Stadium, Kasturba Road',
    'Bangalore',
    'Karnataka',
    '560001',
    12.9696,
    77.5927,
    true,
    '["Recruitment Fair", "Jobs In Bangalore", "Walk-in Interview"]'::jsonb
  ),
  (
    'Ambedkar Community Library & Center',
    'center',
    'A free digital literacy library and career guidance community center supported by regional NGOs, offering coding resources and exam preparation desks.',
    '{"membership_fee": "Free", "target": "Local students and exam aspirants"}'::jsonb,
    'https://hyderabad-community-libs.org/',
    'lib-support@hyderabad-community-libs.org',
    'Kachiguda',
    'Hyderabad',
    'Telangana',
    '560027',
    17.3887,
    78.4900,
    true,
    '["Library", "Study Space", "Community Hub"]'::jsonb
  );
